runtime: php74

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.html
handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /fonts
  static_dir: fonts
  
- url: /scss
  static_dir: scss
